### ISSUE TITLE
since update this morning nothing works

### ISSUE THREAD

**Issue by bitstreamout** [craigmiskell/cookiemaster#11]
As text says, nothing goes here

**Comment by ArcticGems** [comment]
Can you give more details, is it the same as this issue? = https://github.com/craigmiskell/cookiemaster/issues/9

**Comment by bitstreamout** [comment]
Don't think so.   Sometimes site do warn about not accepted cookies even if enabled, sometimes I see simply nothing, here it helps to go into Cookie Quick Manager and delete all cookies corresponding to a site and reload it afterwards.  But for e.g. .fuze.com nothing helps at all. That is it seems that Iß'm not able to reach my fuze account.

**Comment by craigmiskell** [comment]
@bitstreamout Sounds like an issue reported from another user re hushmail.com complaining about cookies not being enabled, particularly as you say "Sometimes site do warn about not accepted cookies even if enabled".  

As part of the most recent update I changed how cookies set by Javascript are captured; the previous way wasn't terribly reliable at correlating which tab the cookie had been set from (the information wasn't directly available and I had to employ some guess work) and had to delete the cookie after it was set, which meant it was set for a very short period.  Cookie-master now hooks more directly into the cookie setting (using a content script), but that then has to use an async call to the webextension background script to check if the cookie should be allowed or not, and another async call back to the content script to actually set it.  It makes it more reliable at knowing where the cookie came from, but introduces async and delays.

It turns out hushmail and possibly others have javascript that sets a cookie and then immediately reads it back again, and if it doesn't retrieve the same value it set, assumes (not unreasonably) that cookies are not enabled.  If that code waited a bit and let the async calls happen, it'd be fine, but it has no idea they're there and has no reason to do so.

I have an idea of how I can rewrite things to make this work, but it'll be a couple of days before I have enough time to get deeply into it.  

Sorry for the inconvenience, this update supposed to make things a lot better, not worse :(

**Comment by craigmiskell** [comment]
@bitstreamout If you can share some specific sites that don't work at all (where you "see simply nothing"), and some where you get warned about not accepting cookies, that would help me test the before and after of the fix, to be sure I've gotten it all.

**Comment by bitstreamout** [comment]
The warning is from mail.vodafon.de ... the missing login is from www.fuze.com after I had said that I do not have a camera as well as no microphone.  The seeing nothing was from https://www.heise.de/newsticker/classic/  (but this works now after clearing all cookies with the help of the Cookies Quick Manager) ... maybe Cookies Quick Manager and CookieMaster interfere

**Comment by craigmiskell** [comment]
Thanks, I'll have a good look tomorrow.  I've gotten some code that I think is working, but it's getting late here now and I need to look at it calmly and clearly when I'm fully awake tomorrow.  With luck I'll get a release out inside the next 24 hours that fixes it.

**Comment by craigmiskell** [comment]
Just submitted version 1.1.2 to addons.mozilla.org (should be available in a few minutes) that fixes the obvious cases here (hushmail.com, mail.vodafone.de).  NB: v1.1.1 still had some debugging (an alert box), so if you find yourself getting alert boxes when you change settings, try forcing an upgrade to 1.1.2 from about:addons.

@bitstreamout I couldn't see what was wrong with www.heise.de even with version 1.1.0, so after the release, if it's still a problem, can you supply much more detail about 'seeing nothing' (i.e. what exactly did you expect to see, and where).  Not sure about fuze.com, so again, check with v1.1.1 and let me know exactly what you see/do not see at which steps, so I can replicate it.
