### ISSUE TITLE
Not saving cookie settings on allowed sites

### ISSUE THREAD

**Issue by audio101** [craigmiskell/cookiemaster#26]
Some websites are asking to re-login/sign-in again upon returning, after having already set the websites to ticked/green, & cookie settings were already previously set.

e.g.'s: 

https://7plus.com.au/live-tv
https://www.9now.com.au/live/channel-9

[Waterfox G4.1.5 (64-bit)]

**Comment by audio101** [comment]
When "Privacy &  Security" set to "Strict", causes this issue. When set to "Standard", site(s( work ok.

**Comment by audio101** [comment]
Seems to be an issue with "Offline website data" when clearing the browser history?

When option is ticked, it does not save certain login settings/data for sites that require it & wipes any previous site configuration.

**Comment by craigmiskell** [comment]
1. I unable to even attempt to replicate because both the indicated sites are Australian-access only (7plus T&Cs require being in Australia, and 9now gives a specific geoblock message when trying to create an account)
2. If the site requires a sign-in again, it implies that the session material hasn't been stored/kept.  That might be because CookieMaster prevented it being stored, or it could be something else. 
   1. Have you tried in a separate browser profile without CookieMaster installed, to confirm whether it's CookieMaster specific?
   2.  Assuming Waterfox allows you to see if cookies and site data are stored, can you confirm that there are any for those domains, after you've logged in, and then later when returning but before logging in again?  Upstream Firefox doesn't offer a way inspect the specific data, but an extension like "CookieManager - Cookie Editor" does, and that might show something useful when you're logged in vs returning (any difference would be interesting).

If none of that is enlightening, there are logs which might be useful.  In the CookieMaster menu, click 'Logs' to open the log viewer.  To keep it limited, it's best to open a fresh browser instance (or a test profile?), "Clear" the logs if any are showing, then visit only the problem site and login.  Then copy and send the logs to cookiemaster@stroppykitten.com rather than on this issue, because there may be sensitive information in some of it.  INFO level is a good start; I may need DEBUG level later, but better to start lighter.  What I hope to see is whether CookieMaster is accepting or rejecting any login-related cookies.

**Comment by audio101** [comment]
Hello, thanks for your reply & tips.

For now I can report that this issue seems to occur on a few websites after clearing the browser history (even if cookies are set to not be cleared/unticked). If the browser history is not cleared & re-login/site settings are set, it doesn't do this issue. 

If the browser history is cleared, some sites ask to re-login again (when previously not signed out), or on a site that requires SMS verification before login, it does not trust the browser & always asks for a verification code again when it was previously set/saved to trust the browser (i.e. set to not always ask for a verification code on each login).

Here is my Waterfox clear history settings:

![Browser clear history](https://user-images.githubusercontent.com/90048453/222930787-f05447d7-4db4-4131-9d43-5b58a77f37d9.png)

Will try do more testing as per your info.

**Comment by craigmiskell** [comment]
It's possible they're storing your identity/session/login information in "Offline web site data", in which case clearing that would log you out.

**Comment by audio101** [comment]
Yes that's what I thought, I previously unchecked "Offline web site data" & it worked for a while & thought it was a fix, then it started doing it again & therefore had to re-open the case. I'll leave it unchecked & report back again if it still does it.

**Comment by audio101** [comment]
Just an update to confirm that ticking "Offline web site data" seems to be the cause of the issue. If that option is ticked & the browser history is cleared (even if cookies are not cleared/saved), it will still clear previously saved website information for certain websites that specifically require it.

After clearing all history & restarting the browser, when ticked, results in undesirable behaviour such as automatically logging you out of certain websites (when was previously already logged in), or asking for authentication again (when browser was previously already trusted).

In order to not have to repeat the process every time, the "Offline web site data" option (under menu "History" -> "Clear Recent History...") must be left unchecked in order to save all the site's settings.

**Comment by audio101** [comment]
Hello,

I've had to reopen this issue because it's still not saving website preferences/data indefinitely (i.e. asking for authentication again when the browser was previously already trusted & also logging you out of certain websites when was previously already logged in), despite trying to figure out what it could be doing this. Unless it's a Waterfox browser bug/behaviour, if anyone has any ideas to fix this issue please comment below. Thanks.

**Comment by audio101** [comment]
Final update:  This issue was only occurring with a few certain websites which were not saving settings, but are now working. I think it's not related to the program but are coding bugs on the website's end, so will therefore close this thread/issue. Thanks.
