### ISSUE TITLE
Cookie defined in site list blocked

### ISSUE THREAD

**Issue by dcfou** [craigmiskell/cookiemaster#28]
Here is parts of log : 

`<html><body>

25/09/2023 11:34:59 | INFO | 1545: Blocking first party cookie in header for .fnac.com
-- | -- | --
25/09/2023 11:34:59 | INFO | 1545: Setting allOK to false  because https://secure.fnac.com/ was not allowed (x 3)
25/09/2023 11:34:59 | INFO | Allowing cookie-change cookie for .fnac.com in catch-all event
25/09/2023 11:34:59 | INFO | Javascript cookie allowed on https://secure.fnac.com/identity/server/gateway/signin-signup
 

</body>
</html>
...
<html><body>

25/09/2023 11:33:48 | INFO | 1497: Blocking first party cookie in header for .fnac.com
-- | -- | --
25/09/2023 11:33:48 | INFO | 1497: Setting allOK to false  because https://secure.fnac.com/ was not allowed (x 3)
25/09/2023 11:33:48 | INFO | Allowing cookie-change cookie for .fnac.com in catch-all event
25/09/2023 11:33:48 | INFO | Javascript cookie allowed on https://secure.fnac.com/identity/server/gateway/signin-signup
 

</body>
</html>`

All this is in the list, even if the first one should be enough :
*.fnac.com
.fnac.com
fnac.com
secure.fnac.com

I had to disable the extension in order to log in, then re-enable it.

**Comment by craigmiskell** [comment]
I'm afraid this is a bug on the website, not in Cookiemaster.  It's setting a cookie with an invalid `domain` field, passing a *url* rather than a domain name:

```
set-cookie: kameleoonVisitorCode=<randomid>; domain=https://secure.fnac.com/; path=/
```

compared to something valid from the same site like:
```
set-cookie: datadome=<randomid>;  Max-Age=31536000; Domain=.fnac.com; Path=/; Secure; SameSite=Lax
```

This is entirely outside the cookies spec (https://datatracker.ietf.org/doc/html/rfc6265).  While I could add some special-case handling to cookie-master, that would be encouraging/allowing some pretty poor behavior and I'm not inclined to do so.
