### ISSUE TITLE
Isn't it possible to interact with the FF cookie settings itself?

### ISSUE THREAD

**Issue by yoshimo** [craigmiskell/cookiemaster#4]
The addon complains about the "block all cookies" setting of Firefox.
Does the FF addon api not allow you to manage the cookie whitelist of firefox directly so you can block all and whitelist only the websites that need cookies to work?

**Comment by craigmiskell** [comment]
You are correct, there is no WebExtension API that lets the extension interact with the built-in whitelists, which is a real shame.

However, CookieMaster should (unless it has bugs) be able to fully manage which cookies are set or blocked.

The complaint is just a reminder/warning, because if 'block all cookies' is set then it doesn't matter what CookieMaster allows through, Firefox will then block it.  At least one user found this confusing and took a while to figure out what was going on.
